# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucPx9B83pdI1HLhzzoW1KJ5Jw-kpDTUF
"""

!pip install streamlit

import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import pickle

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load model and tokenizer from Drive
model = load_model('/content/drive/MyDrive/next_word_GRU.keras')

with open('/content/drive/MyDrive/tokenizer.pkl', 'rb') as f:
    tokenizer = pickle.load(f)

model.summary()

max_sequence_len = 14

def predict_next_word(input_text):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = token_list[-(max_sequence_len-1):]  # truncate if needed
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

    predicted_probs = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predicted_probs, axis=-1)[0]

    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word
    return ""

st.title("Next Word Predictor")
user_input = st.text_input("Enter a sequence of words:")

if st.button("Predict Next Word"):
    if user_input.strip():
        next_word = predict_next_word(user_input)
        st.write(f"Next predicted word: **{next_word}**")
    else:
        st.write("Please enter some text.")

